services:
  - type: web
    name: tag-coding-platform
    env: docker
    region: oregon
    plan: free
    rootDir: Backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: tagDB
      - key: CORS_ORIGIN
        sync: false
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
      - key: REFRESH_TOKEN_EXPIRY
        value: 10d
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
